export const FETCH_ADVENTURE = 'FETCH_ADVENTURE';
export const FETCH_ADVENTURE_SUCCESSFUL = 'FETCH_ADVENTURE_SUCCESSFUL';
export const FETCH_ADVENTURE_FAIL = 'FETCH_ADVENTURE_FAIL';
export const ADD_TO_LIBRARY = 'ADD_TO_LIBRARY';
export const REMOVE_FROM_LIBRARY = 'REMOVE_FROM_LIBRARY';
