export const FETCH_DRAFTS = 'FETCH_DRAFTS';
export const FETCH_DRAFTS_SUCCESS = 'FETCH_DRAFTS_SUCCESS';
export const FETCH_DRAFTS_FAIL = 'FETCH_DRAFTS_FAIL';
export const CREATE_DRAFT = 'CREATE_DRAFT';
export const CREATE_DRAFT_SUCCESS = 'CREATE_DRAFT_SUCCESS';
export const CREATE_DRAFT_FAIL = 'CREATE_DRAFT_FAIL';
export const ADD_STORY_PART = 'ADD_STORY_PART';
export const CHANGE_STORY_PART_KEY = 'CHANGE_STORY_PART_KEY';
export const SELECT_STORY_PART_NEXT_BRANCH_ID =
  'SELECT_STORY_PART_NEXT_BRANCH_ID';
export const ADD_USER_CHOICE = 'ADD_USER_CHOICE';
export const DELETE_DRAFT = 'DELETE_DRAFT';
export const SAVE_STORY_PART = 'SAVE_STORY_PART';
