export const ADD_TO_READ_LIST = 'ADD_TO_READ_LIST';
export const FETCH_STORIES = 'FETCH_STORIES';
export const FETCH_STORIES_SUCCESSFUL = 'FETCH_STORIES_SUCCESSFUL';
export const FETCH_STORY = 'FETCH_STORY';
export const FETCH_STORY_SUCCESSFUL = 'FETCH_STORY_SUCCESSFUL';
