module.exports = {
  getUserByProviderId: require('./getUserByProviderId'),
  getUserById: require('./getUserById'),
  createUser: require('./createUser'),
  createAdventure: require('./createAdventure'),
  getAdventuresByAuthor: require('./getAdventuresByAuthor'),
  getAuthors: require('./getAuthors'),
  getAdventure: require('./getAdventure'),
  updateAdventure: require('./updateAdventure'),
  getPublishedAdventures: require('./getPublishedAdventures'),
  insertAdventureReader: require('./insertAdventureReader'),
  deleteAdventureReader: require('./deleteAdventureReader'),
  deleteDraft: require('./deleteDraft'),
  getGenres: require('./getGenres'),
  getGenre: require('./getGenre'),
};
