module.exports = {
  getUserByProviderId: require('./getUserByProviderId'),
  createUser: require('./createUser'),
  getAdventuresByAuthor: require('./getAdventuresByAuthor'),
  getAuthors: require('./getAuthors'),
  getAdventure: require('./getAdventure'),
  getPublishedAdventures: require('./getPublishedAdventures'),
  deleteAdventureReader: require('./deleteAdventureReader'),
  deleteDraft: require('./deleteDraft'),
  getGenres: require('./getGenres'),
  getGenre: require('./getGenre'),
  getUserLibrary: require('./getUserLibrary'),
  upsertAdventure: require('./upsertAdventure'),
  upsertAdventureReader: require('./upsertAdventureReader'),
  getProgress: require('./getProgress'),
  getUserByUsername: require('./getUserByUsername'),
  updateUser: require('./updateUser'),
};
