module.exports = {
  getUserByProviderId: require('./getUserByProviderId'),
  getUserById: require('./getUserById'),
  createUser: require('./createUser'),
  getAdventuresByAuthor: require('./getAdventuresByAuthor'),
  getAuthors: require('./getAuthors'),
  getAdventure: require('./getAdventure'),
  getPublishedAdventures: require('./getPublishedAdventures'),
  deleteAdventureReader: require('./deleteAdventureReader'),
  deleteDraft: require('./deleteDraft'),
  getGenres: require('./getGenres'),
  getGenre: require('./getGenre'),
  getUserLibrary: require('./getUserLibrary'),
  upsertAdventure: require('./upsertAdventure'),
  upsertAdventureReader: require('./upsertAdventureReader'),
};
