// Editor
export const FETCH_DRAFTS_AUTHORED_BY_USER = 'FETCH_DRAFTS_AUTHORED_BY_USER';
export const FETCH_PUBLISHED_ADVENTURES_AUTHORED_BY_USER =
  'FETCH_PUBLISHED_ADVENTURES_AUTHORED_BY_USER';
export const FETCH_ADVENTURES_AUTHORED_BY_USER_SUCCESS =
  'FETCH_ADVENTURES_AUTHORED_BY_USER_SUCCESS';
export const FETCH_ADVENTURES_AUTHORED_BY_USER_FAIL =
  'FETCH_ADVENTURES_AUTHORED_BY_USER_FAIL';
export const CREATE_DRAFT = 'CREATE_DRAFT';
export const CREATE_DRAFT_FAIL = 'CREATE_DRAFT_FAIL';
export const ADD_STORY_PART = 'ADD_STORY_PART';
export const CHANGE_STORY_PART_KEY = 'CHANGE_STORY_PART_KEY';
export const SELECT_STORY_PART_NEXT_BRANCH_ID =
  'SELECT_STORY_PART_NEXT_BRANCH_ID';
export const ADD_USER_CHOICE = 'ADD_USER_CHOICE';
export const REMOVE_USER_CHOICE = 'REMOVE_USER_CHOICE';
export const DELETE_DRAFT = 'DELETE_DRAFT';
export const SAVE_STORY_PART = 'SAVE_STORY_PART';
export const FETCH_GENRES = 'FETCH_GENRES';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const CHANGE_GENRE = 'CHANGE_GENRE';
export const PUBLISH_ADVENTURE = 'PUBLISH_ADVENTURE';
export const PUBLISH_ADVENTURE_SUCCESS = 'PUBLISH_ADVENTURE_SUCCESS';
export const SAVE_ADVENTURE_SUCCESS = 'SAVE_ADVENTURE_SUCCESS';
export const CHANGE_COVER_IMAGE = 'CHANGE_COVER_IMAGE';
export const REMOVE_COVER_IMAGE = 'REMOVE_COVER_IMAGE';

// Shared
export const AUTHENTICATED = 'AUTHENTICATED';
export const LOG_OUT = 'LOG_OUT';
