// Editor
export const FETCH_DRAFTS_AUTHORED_BY_USER = 'FETCH_DRAFTS_AUTHORED_BY_USER';
export const FETCH_PUBLISHED_ADVENTURES_AUTHORED_BY_USER =
  'FETCH_PUBLISHED_ADVENTURES_AUTHORED_BY_USER';
export const FETCH_ADVENTURES_AUTHORED_BY_USER_SUCCESS =
  'FETCH_ADVENTURES_AUTHORED_BY_USER_SUCCESS';
export const FETCH_ADVENTURES_AUTHORED_BY_USER_FAIL =
  'FETCH_ADVENTURES_AUTHORED_BY_USER_FAIL';
export const CREATE_DRAFT = 'CREATE_DRAFT';
export const CREATE_DRAFT_FAIL = 'CREATE_DRAFT_FAIL';
export const ADD_STORY_PART = 'ADD_STORY_PART';
export const CHANGE_STORY_PART_KEY = 'CHANGE_STORY_PART_KEY';
export const SELECT_STORY_PART_NEXT_BRANCH_ID =
  'SELECT_STORY_PART_NEXT_BRANCH_ID';
export const ADD_USER_CHOICE = 'ADD_USER_CHOICE';
export const REMOVE_USER_CHOICE = 'REMOVE_USER_CHOICE';
export const DELETE_DRAFT = 'DELETE_DRAFT';
export const SAVE_STORY_PART = 'SAVE_STORY_PART';
export const FETCH_GENRES = 'FETCH_GENRES';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const CHANGE_GENRE = 'CHANGE_GENRE';
export const PUBLISH_ADVENTURE = 'PUBLISH_ADVENTURE';
export const PUBLISH_ADVENTURE_SUCCESS = 'PUBLISH_ADVENTURE_SUCCESS';
export const SAVE_ADVENTURE_SUCCESS = 'SAVE_ADVENTURE_SUCCESS';

// Reader
export const FETCH_ADVENTURE = 'FETCH_ADVENTURE';
export const FETCH_ADVENTURE_SUCCESSFUL = 'FETCH_ADVENTURE_SUCCESSFUL';
export const FETCH_ADVENTURE_FAIL = 'FETCH_ADVENTURE_FAIL';
export const ADD_TO_LIBRARY = 'ADD_TO_LIBRARY';
export const REMOVE_FROM_LIBRARY = 'REMOVE_FROM_LIBRARY';
export const TOGGLE_NIGHT_MODE = 'TOGGLE_NIGHT_MODE';
export const INCREASE_FONT_SIZE = 'INCREASE_FONT_SIZE';
export const DECREASE_FONT_SIZE = 'DECREASE_FONT_SIZE';
export const RESET_FONT_SIZE = 'RESET_FONT_SIZE';
export const CHANGE_FONT_TYPE = 'CHANGE_FONT_TYPE';
export const FETCH_LIBRARY = 'FETCH_LIBRARY';
export const FETCH_LIBRARY_SUCESS = 'FETCH_LIBRARY_SUCESS';

// Shared
export const AUTHENTICATED = 'AUTHENTICATED';
export const LOG_OUT = 'LOG_OUT';
